# Enriquecendo dados para camada Silver

In [1]:
import duckdb

In [2]:
con = duckdb.connect(database = 'dados_duck.db', read_only = False)

In [12]:
df = con.execute("""
                SELECT * 
                FROM (
                SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY data_ingestao DESC) AS row 
                FROM bronze_z0019
                WHERE data_ingestao >= '2026-10-06'
                ) WHERE row = 1

                """).fetchdf()
df.head(10)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao,row
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-10-06 11:56:17.551181,1
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-10-06 11:56:17.551181,1
2,10004,SERRA,BT50,100,200,z0019_2.csv,2026-10-06 20:35:03.101803,1
3,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-10-06 20:35:03.101803,1
4,10003,PREGO,BT10,100,60,z0019_2.csv,2026-10-06 20:35:03.101803,1

In [17]:
df_final = df.drop(columns=['nome_arquivo', 'data_ingestao', 'row'])
df_final = df_final.rename(columns={"NATBR":"id"})
df_final = df_final.rename(columns={"MAKTX":"nm_produto"})
df_final = df_final.rename(columns={"WERKS":"id_categoria"})
df_final = df_final.rename(columns={"MAINS":"id_fornecedor"})
df_final = df_final.rename(columns={"LABST":"vl_preco"})
df_final.head(10)

      id nm_produto id_categoria id_fornecedor vl_preco
0  10001   PARAFUSO         BT10           100      100
1  10002    MARTELO         BT50           100     1500
2  10004      SERRA         BT50           100      200
3  10005    MACHADO         BT50           100      100
4  10003      PREGO         BT10           100       60

NameError: name 'con' is not defined